---
version: 2

defaults: &defaults
  docker:
    - image: circleci/golang:1.11
  environment:
    GOPATH: /go
  working_directory: /go/src/github.com/appvia/hub-grafana-agent

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: make test
      - run: make build


workflows:
  version: 2
  workflow:
    jobs:
    - build
