---
version: 2

defaults: &defaults
  docker:
    - image: circleci/golang:1.11
  environment:
    GOPATH: /go
  working_directory: /go/src/github.com/appvia/hub-grafana-agent

jobs:
  validate_swagger:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: sudo npm i -g swagger
      - run: swagger validate api/swagger.yaml

  build:
    <<: *defaults
    steps:
      - checkout
      - run: make test
      - run: make build


workflows:
  version: 2
  workflow:
    jobs:
    - validate_swagger
    - build
