/*
 * hub-grafana-agent
 *
 * an agent used to provision and configure Grafana resources
 *
 * API version: v1beta
 * Contact: support@appvia.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"bytes"
	"errors"
	"encoding/base64"
	"encoding/json"
	"io"
	"io/ioutil"
	"net/http"
	"text/template"

	"github.com/gorilla/mux"
	logrus "github.com/sirupsen/logrus"
)

const dashboardPrefix string = "hub-grafana-"

func handleSuccess(w http.ResponseWriter, payload []byte) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.Write(payload)
}

func handleDelete(w http.ResponseWriter) {
	w.WriteHeader(http.StatusNoContent)
}

func handleInternalServerError(w http.ResponseWriter, reason string, detail string) {
	var apiError ApiError
	apiError = ApiError{Reason: reason, Detail: detail}
	payload, err := json.Marshal(apiError)
	_ = err
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusInternalServerError)
	w.Write(payload)
}

func handleBadRequest(w http.ResponseWriter, detail string) {
	var apiError ApiError
	apiError = ApiError{Reason: "bad request", Detail: detail}
	payload, err := json.Marshal(apiError)
	_ = err
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusBadRequest)
	w.Write(payload)
}

func handleNotFoundError(w http.ResponseWriter, detail string) {
	var apiError ApiError
	apiError = ApiError{Reason: "not found", Detail: detail}
	payload, err := json.Marshal(apiError)
	_ = err
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusNotFound)
	w.Write(payload)
}

func callGrafana(url string, apiKey string, verb string, payload io.Reader) (int, []byte, error) {
	var statusCode int
	var body []byte
	var err error
	req, err := http.NewRequest(verb, url, payload)
	req.Header.Set("Authorization", "Bearer"+" "+apiKey)
	req.Header.Set("Accept", "application/json")
	client := &http.Client{}
	resp, err := client.Do(req)
	defer resp.Body.Close()
	if err != nil {
		logrus.Println("Error calling Grafana:", verb, url, err)
	} else {
		body, _ = ioutil.ReadAll(resp.Body)
		statusCode = resp.StatusCode
		logrus.Printf("Response body from Grafana: %s", string(body))
		logrus.Printf("Response code from Grafana: %v", statusCode)
	}
	return statusCode, body, err
}

func getTemplateFromUrl(templateUrl string) ([]byte, error) {
	var templateBody []byte
	var err error
	req, err := http.NewRequest("GET", templateUrl, nil)
	req.Header.Set("Accept", "application/json,text/plain")
	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		logrus.Println("Error fetching Grafana dashboard json from URL:", templateUrl)
		return templateBody, err
	}
	defer resp.Body.Close()
	templateBody, _ = ioutil.ReadAll(resp.Body)
	logrus.Println("Template response body:", string(templateBody))
	return templateBody, nil
}

func getDashboardByNamespace(namespace string, grafanaUrl string, grafanaApiKey string) (url string, id int64, uid string, results bool, err error) {

	status, body, err := callGrafana(grafanaUrl+"/api/search?tag="+dashboardPrefix+namespace, grafanaApiKey, "GET", nil)

	if status != 200 || err != nil {
		logrus.Println("Error getting dashboard for namespace:", namespace)
		return
	}

	type GrafanaDashboard struct {
		Uid string `json:"uid"`
		Id  int64  `json:"id"`
		Url string `json:"url"`
	}
	var g []GrafanaDashboard

	if err := json.Unmarshal(body, &g); err != nil {
		panic(err)
	}
	if len(g) == 0 {
		err := errors.New("dashboard not found")
		found := false
		return  url, id, uid, found, err
	} else if len(g) > 1 {
		found := true
		err := errors.New("more than one dashboard found")
		return  url, id, uid, found, err
	}

	dash := g[0]

	url = grafanaUrl + dash.Url
	id = dash.Id
	uid = dash.Uid
	found := true

	return url, id, uid, found, err
}

func DashboardNamespaceDelete(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	namespace := vars["namespace"]

	decodedCert, err := base64.StdEncoding.DecodeString(r.Header.Get("X-Grafana-CA"))
	if err != nil {
		logrus.Println("decode error:", err)
	}
	_ = decodedCert
	grafanaUrl := r.Header.Get("X-Grafana-Url")
	grafanaApiKey := r.Header.Get("X-Grafana-API-Key")

	if err != nil {
		logrus.Println("decode error:", err)
	}

	url, id, uid, results, err := getDashboardByNamespace(namespace, grafanaUrl, grafanaApiKey)

	if results == false {
		_, _, _ = id, uid, url
		handleDelete(w)
		return
	}

	if err != nil {
		handleInternalServerError(w, "internal server error", "error calling Grafana")
		return
	}

	if uid == "" {
		logrus.Println("Dashboard already deleted!")
		handleDelete(w)
		return
	}

	logrus.Printf("Attempting to delete dashboard with uid %s", string(uid))

	status, body, err := callGrafana(grafanaUrl+"/api/dashboards/uid/"+uid, grafanaApiKey, "DELETE", nil)
	_ = body

	if err != nil {
		handleInternalServerError(w, "internal server error", "error deleting dashboard from Grafana")
		return
	}

	if status == 200 {
		logrus.Println("Dashboard deleted!")
		w.WriteHeader(204)
		return
	} else {
		handleInternalServerError(w, "internal server error", "error deleting dashboard from Grafana")
		return
	}
}

func DashboardNamespaceGet(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	namespace := vars["namespace"]

	decodedCert, err := base64.StdEncoding.DecodeString(r.Header.Get("X-Grafana-CA"))
	if err != nil {
		logrus.Println("decode error:", err)
	}
	_ = decodedCert
	grafanaUrl := r.Header.Get("X-Grafana-Url")
	grafanaApiKey := r.Header.Get("X-Grafana-API-Key")

	url, id, uid, results, err := getDashboardByNamespace(namespace, grafanaUrl, grafanaApiKey)

	if results == false {
		handleNotFoundError(w, "dashboard not found")
		return
	}

	if err != nil {
		handleInternalServerError(w, "internal server error", "error calling Grafana")
		return
	}

	var dashboard Dashboard
	dashboard = Dashboard{Namespace: namespace, Url: url, Id: id, Uid: uid}
	payload, err := json.Marshal(dashboard)

	if err != nil {
		logrus.Println(err)
	}

	handleSuccess(w, payload)
	return
}

func renderLocalTemplate(namespace string, id string, uid string) (renderedTemplate io.Reader, err error) {
	type Variables struct {
		Namespace string
	}
	templateVars := Variables{namespace}
	var payload bytes.Buffer
	tmpl := template.Must(template.ParseFiles("dashboards/kubernetes-prometheus.json.tmpl"))
	err = tmpl.Execute(&payload, templateVars)
	if err != nil {
		return
	}
	tmpl.Execute(&payload, templateVars)
	renderedTemplate = &payload
	return renderedTemplate, err
}

func DashboardNamespacePut(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	namespace := vars["namespace"]

	decodedCert, err := base64.StdEncoding.DecodeString(r.Header.Get("X-Grafana-CA"))
	if err != nil {
		logrus.Println("decode error:", err)
	}
	_ = decodedCert
	grafanaUrl := r.Header.Get("X-Grafana-Url")
	grafanaApiKey := r.Header.Get("X-Grafana-API-Key")
	reqBody, err := ioutil.ReadAll(r.Body)

	var useTemplateFromUrl bool
	var templateFromUrl io.Reader
	var templateUrl string
	if len(reqBody) > 0 {
		var t TemplateUrl
		err = json.Unmarshal(reqBody, &t)
		if err != nil || t.Url == "" {
			logrus.Println("Malformed request body:", string(reqBody))
			handleBadRequest(w, "request body malformed")
			return
		}
		templateUrl = t.Url
		logrus.Println("PUT request for namespace:", namespace, "templateUrl:", templateUrl)
		templateFromUrl, err := getTemplateFromUrl(templateUrl)
		logrus.Println("Template body:", string(templateFromUrl))
		if err != nil {
			handleInternalServerError(w, "internal server error", "error fetching template from templateUrl")
			return
		}
		useTemplateFromUrl = true
	} else {
		useTemplateFromUrl = false
	}

	url, id, uid, results, err := getDashboardByNamespace(namespace, grafanaUrl, grafanaApiKey)

	logrus.Printf("Attempting to create dashboard for namespace %s in grafana", namespace)

	var status int64
	if useTemplateFromUrl == true {
		status, body, err := callGrafana(grafanaUrl+"/api/dashboards/db", grafanaApiKey, "POST", templateFromUrl)
		if status != 200 || err != nil {
			logrus.Println(err)
			handleInternalServerError(w, "internal server error", "error creating dashboard from template: " + templateUrl)
			return
		}
	}
	if useTemplateFromUrl == false {
		var renderedTemplate io.Reader
		if results == true {
			renderedTemplate, err := renderLocalTemplate(namespace, string(id), uid)
		} else {
			renderedTemplate, err := renderLocalTemplate(namespace, "null", "null")
		}
		status, body, err := callGrafana(grafanaUrl+"/api/dashboards/db", grafanaApiKey, "POST", renderedTemplate)
	}

	if status != 200 || err != nil {
		logrus.Println(err)
		handleInternalServerError(w, "internal server error", "error creating dashboard in Grafana")
		return
	}

	var dashboard Dashboard
	dashboard = Dashboard{Namespace: namespace, Url: url, Id: id, Uid: uid}
	payload, err := json.Marshal(dashboard)

	handleSuccess(w, payload)
	return
}
