/*
 * hub-grafana-agent
 *
 * an agent used to provision and configure Grafana resources
 *
 * API version: v1beta
 * Contact: support@appvia.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"errors"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"strconv"
	"strings"
	"text/template"

	"github.com/gorilla/mux"
	"github.com/sethvargo/go-password/password"
	logrus "github.com/sirupsen/logrus"
)

const dashboardPrefix string = "hub-grafana-"
const teamName string = "hub-team"

func handleSuccess(w http.ResponseWriter, payload []byte) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.Write(payload)
}

func handleDelete(w http.ResponseWriter) {
	w.WriteHeader(http.StatusNoContent)
}

func handleInternalServerError(w http.ResponseWriter, reason, detail string) {
	var apiError ApiError
	apiError = ApiError{Reason: reason, Detail: detail}
	payload, err := json.Marshal(apiError)
	_ = err
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusInternalServerError)
	w.Write(payload)
}

func handleBadRequest(w http.ResponseWriter, detail string) {
	var apiError ApiError
	apiError = ApiError{Reason: "bad request", Detail: detail}
	payload, err := json.Marshal(apiError)
	_ = err
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusBadRequest)
	w.Write(payload)
}

func handleNotFoundError(w http.ResponseWriter, detail string) {
	var apiError ApiError
	apiError = ApiError{Reason: "not found", Detail: detail}
	payload, err := json.Marshal(apiError)
	_ = err
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusNotFound)
	w.Write(payload)
}

func generatePassword() (passwd string, err error) {
	passwd, err = password.Generate(12, 6, 6, false, false)
	if err != nil {
		logrus.Fatal(err)
		return passwd, err
	}
	return passwd, nil
}

func callGrafana(admin bool, url, auth, verb string, payload io.Reader) (int, []byte, error) {
	var statusCode int
	var body []byte
	var err error
	var authKey string

	if admin {
		logrus.Debugln("Using basic auth")
		authKey = "Basic"
	} else {
		logrus.Debugln("Using bearer auth")
		authKey = "Bearer"
	}

	req, err := http.NewRequest(verb, url, payload)
	req.Header.Set("Authorization", authKey+" "+auth)
	req.Header.Set("Accept", "application/json")
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{}
	resp, err := client.Do(req)
	defer resp.Body.Close()

	if err != nil {
		logrus.Errorln("Error calling Grafana:", verb, url, err)
	} else {
		body, _ = ioutil.ReadAll(resp.Body)
		statusCode = resp.StatusCode
		logrus.Debugf("Response body from Grafana: %s", string(body))
		logrus.Debugf("Response code from Grafana: %v", statusCode)
	}
	return statusCode, body, err
}

func getTemplateFromUrl(templateUrl string) ([]byte, error) {
	var templateBody []byte
	var err error

	req, err := http.NewRequest("GET", templateUrl, nil)
	req.Header.Set("Accept", "application/json,text/plain")
	client := &http.Client{}
	resp, err := client.Do(req)

	if err != nil {
		logrus.Infoln("Error fetching Grafana dashboard json from URL:", templateUrl)
		return templateBody, err
	}

	defer resp.Body.Close()

	templateBody, _ = ioutil.ReadAll(resp.Body)

	logrus.Debugln("Template response body:", string(templateBody))

	return templateBody, nil
}

func getDashboardAlerts(id int64, grafanaURL, grafanaApiKey string) (alerts []GrafanaDashboardAlert, err error) {
	idString := strconv.FormatInt(id, 10)
	logrus.Infoln("Getting alerts for dashboard:", idString)
	status, body, err := callGrafana(false, grafanaURL+"/api/alerts?dashboardId="+idString, grafanaApiKey, "GET", nil)

	err = json.Unmarshal(body, &alerts)

	if status != 200 || err != nil {
		logrus.Errorln("Error getting alerts for dashboard:", idString)
	}
	return alerts, err
}

func getDashboardByName(name, grafanaURL, grafanaApiKey string) (url string, id int64, uid string, version int64, found bool, err error) {

	logrus.Infoln("Searching for dashboard using tag:", dashboardPrefix+name)

	status, body, err := callGrafana(false, grafanaURL+"/api/search?tag="+dashboardPrefix+name, grafanaApiKey, "GET", nil)

	if status == 401 {
		logrus.Errorln("Invalid Grafana API key")
		err = errors.New("Invalid Grafana API key")
		return
	}

	if status == 404 {
		logrus.Errorln("Dashbord not found")
		found = false
		return
	}

	if status != 200 {
		logrus.Infoln("Error getting dashboard for name:", name)
		return
	}

	var g []GrafanaDashboard

	if err := json.Unmarshal(body, &g); err != nil {
		panic(err)
	}

	if len(g) == 0 {
		found = false
		return url, id, uid, version, found, err
	} else if len(g) == 1 {
		found = true
		logrus.Infoln("Found one dashboard matching search")
	} else if len(g) > 1 {
		found = true
		return url, id, uid, version, found, errors.New("more than one dashboard found")
	}

	dash := g[0]

	url = grafanaURL + dash.Url
	id = dash.Id
	uid = dash.Uid
	version = dash.Version

	return url, id, uid, version, found, err
}

func createUser(user User, grafanaURL, auth string) (createdUser User, err error) {
	existingUser, found, err := getUserByEmail(user.Email, grafanaURL, auth)

	if found {
		logrus.Infof("User %s exists already", existingUser.Email)
		return existingUser, nil
	}

	user.Password, err = generatePassword()

	if err != nil {
		return createdUser, err
	}

	payload, err := json.Marshal(user)

	if err != nil {
		return createdUser, err
	}

	payloadReader := bytes.NewReader(payload)

	status, _, err := callGrafana(true, grafanaURL+"/api/admin/users", auth, "POST", payloadReader)

	if status != 200 || err != nil {
		logrus.Infoln("Error creating user")
		return user, err
	}

	createdUser, _, err = getUserByEmail(user.Email, grafanaURL, auth)

	return createdUser, nil
}

func createTeam(teamName, grafanaURL, auth string) (team Team, err error) {

	team, found, err := getTeamByName(teamName, grafanaURL, auth)

	if err == nil && found == true {
		return team, nil
	}

	newTeam := Team{Name: teamName}
	teamObject, err := json.Marshal(newTeam)
	payloadReader := bytes.NewReader(teamObject)

	status, body, err := callGrafana(true, grafanaURL+"/api/teams", auth, "POST", payloadReader)

	if err != nil {
		logrus.Infoln("Error creating team: " + err.Error())
		return team, err
	}

	var grafanaResponse GrafanaCreateTeamResponse
	err = json.Unmarshal(body, &grafanaResponse)

	if status != 200 && status != 409 {
		logrus.Infoln("Error creating team: " + teamName + "response status from grafana: " + strconv.Itoa(status))
		return team, errors.New("Error creating team:" + teamName)
	}
	teamResponse := Team{Name: teamName, TeamId: grafanaResponse.TeamId}
	return teamResponse, nil
}

func getUserByEmail(email, grafanaURL, auth string) (user User, found bool, err error) {
	logrus.Infoln("Searching for user using email:", email)

	status, body, err := callGrafana(true, grafanaURL+"/api/users/lookup?loginOrEmail="+email, auth, "GET", nil)

	if err != nil {
		logrus.Infoln("Error getting user for email:", email)
		return
	}

	var u User

	if status == 404 {
		logrus.Infoln("User not found")
		found = false
		return u, found, err
	} else {
		logrus.Infoln("User found")
		found = true
		err := json.Unmarshal(body, &u)
		return u, found, err
	}
}

func deleteUserByEmail(email, grafanaURL, auth string) (err error) {
	logrus.Infoln("Searching for user using email:", email)

	user, found, err := getUserByEmail(email, grafanaURL, auth)

	if err != nil {
		logrus.Infoln("Error deleting user for email:", email)
		return err
	}

	if found == false {
		logrus.Infoln("User not found")
		return nil
	}

	logrus.Infoln("User found, deleting...")
	status, _, err := callGrafana(true, grafanaURL+"/api/admin/users/"+strconv.FormatInt(user.Id, 10), auth, "DELETE", nil)

	if err != nil || status != 200 {
		return err
	}
	return
}

func deleteUserById(id int64, grafanaURL, auth string) (err error) {
	if id == 1 {
		logrus.Infof("Skipping deletion of admin user...")
		return nil
	}
	var idString string = strconv.FormatInt(id, 10)
	status, _, err := callGrafana(true, grafanaURL+"/api/admin/users/"+idString, auth, "DELETE", nil)

	if err != nil || status != 200 {
		logrus.Errorf("Failed to delete user with ID:" + idString)
		return err
	}
	return
}

func addUserToTeam(user User, team Team, grafanaURL, auth string) (err error) {
	logrus.Infof("Adding user %s to team %s", user.Email, team.Name)

	member := TeamMember{UserId: user.Id}
	memberObject, err := json.Marshal(member)

	teamId := strconv.FormatInt(team.TeamId, 10)

	memberPayload := bytes.NewReader(memberObject)

	status, _, err := callGrafana(true, grafanaURL+"/api/teams/"+teamId+"/members", auth, "POST", memberPayload)

	if err != nil {
		logrus.Errorf("Error adding user to team %s", teamId)
		return
	}

	if status == 400 || status == 200 {
		logrus.Infof("User %s added to team %s", strconv.FormatInt(user.Id, 10), teamId)
		return
	} else {
		logrus.Errorf("Error adding user %s to team %s", strconv.FormatInt(user.Id, 10), teamId)
		return
	}
}

func checkTeamMembership(email string, team Team, grafanaURL, auth string) (user User, found bool, err error) {
	logrus.Infof("Checking user %s is in team %s:", email, team.Name)

	teamId := strconv.FormatInt(team.TeamId, 10)

	status, body, err := callGrafana(true, grafanaURL+"/api/teams/"+teamId+"/members", auth, "GET", nil)

	if err != nil || status != 200 {
		logrus.Errorln("Error checking team membership")
		return
	}

	var u User

	if len(body) == 0 {
		logrus.Infoln("User not found")
		found = false
		return u, found, err
	} else {
		logrus.Infoln("User found")
		found = true
		err := json.Unmarshal(body, &u)
		return u, found, err
	}
}

func getTeamMembers(team Team, grafanaURL, auth string) (users []User, err error) {
	logrus.Infof("Getting members of team: %s", team.Name)

	teamId := strconv.FormatInt(team.TeamId, 10)

	status, body, err := callGrafana(true, grafanaURL+"/api/teams/"+teamId+"/members", auth, "GET", nil)

	logrus.Infoln("Response from membership list:")
	logrus.Infoln(string(body))

	if err != nil || status != 200 {
		logrus.Errorln("Error checking team membership")
		return users, err
	}

	var members []TeamMember
	err = json.Unmarshal(body, &members)

	for _, m := range members {
		user, _, err := getUserByEmail(m.Email, grafanaURL, auth)
		if err != nil {
			return users, err
		}
		users = append(users, user)
	}

	if err != nil {
		logrus.Infoln("Malformed response from Grafana")
		return users, err
	}
	return users, nil
}

func getTeamByName(name, grafanaURL, auth string) (team Team, found bool, err error) {
	logrus.Infoln("Searching for team by name:", name)

	status, body, err := callGrafana(true, grafanaURL+"/api/teams/search?name="+name, auth, "GET", nil)

	if err != nil {
		logrus.Errorln("Error getting team with the name:", name)
		return
	}

	var g GrafanaGetTeamResponse
	err = json.Unmarshal(body, &g)

	if err != nil {
		logrus.Errorln("Error getting team with the name:", name)
		return
	}

	var t Team

	if status == 404 {
		logrus.Infoln("Team not found")
		found = false
		return t, found, err
	}

	if status == 200 && len(g.Teams) == 1 {
		t = g.Teams[0]
		if err != nil {
			logrus.Errorln("Error getting team with the name:", name)
		}
		logrus.Infoln("Team found")
		found = true
		return t, found, err
	} else {
		logrus.Infoln("No team found:", name)
		found = false
		return t, found, err
	}
}

func DashboardNameDelete(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	name := vars["name"]

	_, err := base64.StdEncoding.DecodeString(r.Header.Get("X-Grafana-CA"))
	if err != nil {
		logrus.Errorln("decode error:", err)
	}
	grafanaURL := strings.TrimRight(r.Header.Get("X-Grafana-Url"), "/")
	grafanaApiKey := r.Header.Get("X-Grafana-API-Key")

	if err != nil {
		logrus.Errorln("decode error:", err)
	}

	url, id, uid, _, found, err := getDashboardByName(name, grafanaURL, grafanaApiKey)

	if err != nil {
		handleInternalServerError(w, "internal server error", "error searching for dashboard in Grafana")
		return
	}

	if found == false {
		_, _, _ = id, uid, url
		handleDelete(w)
		return
	}

	if err != nil {
		handleInternalServerError(w, "internal server error", "error calling Grafana")
		return
	}

	if uid == "" {
		logrus.Infoln("Dashboard already deleted!")
		handleDelete(w)
		return
	}

	logrus.Infof("Attempting to delete dashboard with uid %s", string(uid))

	status, _, err := callGrafana(false, grafanaURL+"/api/dashboards/uid/"+uid, grafanaApiKey, "DELETE", nil)

	if err != nil {
		handleInternalServerError(w, "internal server error", "error deleting dashboard from Grafana")
		return
	}

	if status == 200 {
		logrus.Infoln("Dashboard deleted!")
		w.WriteHeader(204)
		return
	} else {
		handleInternalServerError(w, "internal server error", "error deleting dashboard from Grafana")
		return
	}
}

func DashboardNameGet(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	name := vars["name"]

	_, err := base64.StdEncoding.DecodeString(r.Header.Get("X-Grafana-CA"))
	if err != nil {
		logrus.Infoln("decode error:", err)
	}
	grafanaURL := strings.TrimRight(r.Header.Get("X-Grafana-Url"), "/")
	grafanaApiKey := r.Header.Get("X-Grafana-API-Key")

	url, id, uid, _, found, err := getDashboardByName(name, grafanaURL, grafanaApiKey)

	if err != nil {
		handleInternalServerError(w, "internal server error", "error searching for dashboard in Grafana")
		return
	}

	if !found {
		handleNotFoundError(w, "dashboard not found")
		return
	}

	var dashboard GrafanaDashboard
	dashboard = GrafanaDashboard{Name: name, Url: url, Id: id, Uid: uid}
	payload, err := json.Marshal(dashboard)

	if err != nil {
		logrus.Errorln(err)
	}

	handleSuccess(w, payload)
	return
}

func DashboardAlertsNameGet(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	name := vars["name"]

	_, err := base64.StdEncoding.DecodeString(r.Header.Get("X-Grafana-CA"))
	if err != nil {
		logrus.Infoln("decode error:", err)
	}
	grafanaURL := strings.TrimRight(r.Header.Get("X-Grafana-Url"), "/")
	grafanaApiKey := r.Header.Get("X-Grafana-API-Key")

	_, id, _, _, found, err := getDashboardByName(name, grafanaURL, grafanaApiKey)

	if err != nil {
		logrus.Errorln("Error retrieving dashboard:", name)
		handleInternalServerError(w, "Error retrieving dashboard: "+name, err.Error())
		return
	}

	if !found {
		handleNotFoundError(w, "Dashboard not found")
		return
	}

	alerts, err := getDashboardAlerts(id, grafanaURL, grafanaApiKey)

	if err != nil {
		logrus.Errorln("Error retrieving alerts for dashboard")
		handleInternalServerError(w, "Error retrieving alerts for dashboard", err.Error())
		return
	}

	var updatedAlerts []GrafanaDashboardAlert

	for _, alert := range alerts {
		var updatedAlert GrafanaDashboardAlert
		updatedAlert = alert
		updatedAlert.Url = grafanaURL + alert.Url
		updatedAlerts = append(updatedAlerts, updatedAlert)
	}

	responseBody, err := json.Marshal(updatedAlerts)

	if err != nil {
		panic(err)
	}

	handleSuccess(w, responseBody)
	return
}

func renderTemplate(name, id, uid, version, templateAsString string) (renderedTemplate io.Reader, err error) {
	templateVars := Variables{name, id, uid, version}
	var payload bytes.Buffer
	t := template.New("dashboard")
	t.Parse(templateAsString)
	err = t.Execute(&payload, templateVars)

	logrus.Debugln("Rendered dashboard template:")
	logrus.Debugln(t.Execute(os.Stdout, templateVars))

	if err != nil {
		return
	}
	renderedTemplate = &payload
	return renderedTemplate, err
}

func DashboardNamePut(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	name := vars["name"]

	_, err := base64.StdEncoding.DecodeString(r.Header.Get("X-Grafana-CA"))
	if err != nil {
		logrus.Errorln("decode error:", err)
	}
	grafanaURL := strings.TrimRight(r.Header.Get("X-Grafana-Url"), "/")
	grafanaApiKey := r.Header.Get("X-Grafana-API-Key")
	reqBody, err := ioutil.ReadAll(r.Body)

	if err != nil {
		panic(err)
	}

	if len(reqBody) == 0 {
		logrus.Infoln("Malformed request body:", string(reqBody))
		handleBadRequest(w, "request body malformed")
		return
	}

	var t TemplateUrl
	err = json.Unmarshal(reqBody, &t)
	if err != nil || t.Url == "" {
		logrus.Infoln("Malformed request body:", string(reqBody))
		handleBadRequest(w, "request body malformed")
		return
	}

	templateUrl := t.Url
	logrus.Infoln("PUT request for name:", name, "templateUrl:", templateUrl)
	templateFromUrl, err := getTemplateFromUrl(templateUrl)

	if err != nil {
		handleInternalServerError(w, "internal server error", "error fetching template from templateUrl")
		return
	}

	url, id, uid, version, found, err := getDashboardByName(name, grafanaURL, grafanaApiKey)

	if err != nil {
		handleInternalServerError(w, "internal server error", "error searching for dashboard in Grafana")
		return
	}

	var idVar, uidVar, versionVar string
	if found == false {
		idVar, uidVar, versionVar = "null", "null", "1"
		logrus.Infoln("Dashboard not found, creating new")
	} else {
		idVar, uidVar = strconv.FormatInt(id, 10), "\""+uid+"\""
		versionVar = strconv.FormatInt(version+1, 10)
		logrus.Infof("Dashboard found id: %s uid: %s version: %s", idVar, uidVar, strconv.FormatInt(version, 10))
		logrus.Infof("Updating existing dashboard id: %s uid: %s version: %s", idVar, uidVar, versionVar)
	}

	logrus.Infof("Attempting to create dashboard for name %s in grafana", name)

	renderedTemplateFromUrl, err := renderTemplate(name, idVar, uidVar, versionVar, string(templateFromUrl))

	if err != nil {
		logrus.Errorln(err)
		return
	}

	status, body, err := callGrafana(false, grafanaURL+"/api/dashboards/db", grafanaApiKey, "POST", renderedTemplateFromUrl)

	if status != 200 || err != nil {
		logrus.Errorln(err)
		handleInternalServerError(w, "internal server error", "error creating dashboard from template: "+templateUrl)
		return
	}

	var g GrafanaDashboard
	if err := json.Unmarshal(body, &g); err != nil {
		handleInternalServerError(w, "internal server error", "Unexpected response from Grafana")
		return
	}

	url = grafanaURL + g.Url
	id = g.Id
	uid = g.Uid

	var dashboard GrafanaDashboard
	dashboard = GrafanaDashboard{Name: name, Url: url, Id: id, Uid: uid}
	responseBody, err := json.Marshal(dashboard)

	handleSuccess(w, responseBody)
	return
}

func UserGet(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	email := vars["email"]

	_, err := base64.StdEncoding.DecodeString(r.Header.Get("X-Grafana-CA"))
	if err != nil {
		logrus.Errorln("decode error:", err)
	}
	grafanaURL := strings.TrimRight(r.Header.Get("X-Grafana-Url"), "/")
	grafanaBasicAuth := r.Header.Get("X-Grafana-Basic-Auth")

	logrus.Infoln("Getting user by email:", email)

	user, found, err := getUserByEmail(email, grafanaURL, grafanaBasicAuth)

	if err != nil {
		logrus.Errorln("Error getting user for email:", email)
		return
	}

	if found == false {
		handleNotFoundError(w, "User not found")
		return
	}

	responseBody, err := json.Marshal(user)

	handleSuccess(w, responseBody)
}

func UserDelete(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	email := vars["email"]

	_, err := base64.StdEncoding.DecodeString(r.Header.Get("X-Grafana-CA"))
	if err != nil {
		logrus.Errorln("decode error:", err)
	}
	grafanaURL := strings.TrimRight(r.Header.Get("X-Grafana-Url"), "/")
	grafanaBasicAuth := r.Header.Get("X-Grafana-Basic-Auth")

	logrus.Infoln("Getting user by email:", email)

	user, found, err := getUserByEmail(email, grafanaURL, grafanaBasicAuth)

	if err != nil {
		logrus.Errorln("Error getting user for email: " + email)
		handleInternalServerError(w, "internal server error", "error checking user existence: "+user.Email)
	}

	if found == false {
		logrus.Infoln("Delete request for non existent user:", email)
		handleDelete(w)
		return
	}

	err = deleteUserByEmail(email, grafanaURL, grafanaBasicAuth)

	if err != nil {
		handleInternalServerError(w, "internal server error", "error deleting user: "+email)
	}
	handleDelete(w)
}

func userInList(user User, list []User) bool {
	for _, u := range list {
		if u.Id == user.Id {
			return true
		}
	}
	return false
}

func removeUserFromTeam(user User, team Team, grafanaURL, auth string) (err error) {
	status, _, err := callGrafana(true, grafanaURL+"/api/teams/"+strconv.FormatInt(team.TeamId, 10)+"/members/"+strconv.FormatInt(user.Id, 10), auth, "DELETE", nil)

	if err != nil {
		logrus.Errorf("Error removing user %s from team %s", user.Name, team.Name)
		return
	}

	if status == 404 {
		logrus.Infof("User not in team")
		return nil
	}

	if status == 200 {
		logrus.Infof("User %s removed from team %s", user.Name, team.Name)
		return nil
	}
	return
}

func getAllUsers(grafanaURL, auth string) (userList []User, err error) {
	status, body, err := callGrafana(true, grafanaURL+"/api/users?perpage=1000&page=1", auth, "GET", nil)

	if status != 200 || err != nil {
		logrus.Errorln("Error listing all users")
		return
	}

	err = json.Unmarshal(body, &userList)

	if err != nil {
		logrus.Errorln("Error listing all users, malformed response from grafana")
		return
	}

	return userList, nil
}

func UsersPut(w http.ResponseWriter, r *http.Request) {
	_, err := base64.StdEncoding.DecodeString(r.Header.Get("X-Grafana-CA"))

	if err != nil {
		logrus.Errorln("decode error:", err)
	}

	grafanaURL := strings.TrimRight(r.Header.Get("X-Grafana-Url"), "/")
	grafanaBasicAuth := r.Header.Get("X-Grafana-Basic-Auth")
	reqBody, err := ioutil.ReadAll(r.Body)

	if len(reqBody) == 0 {
		logrus.Infoln("Missing request body:", string(reqBody))
		handleBadRequest(w, "request body malformed")
		return
	}

	var users []User
	err = json.Unmarshal(reqBody, &users)

	if err != nil {
		logrus.Infoln("Malformed request body:", string(reqBody), err.Error())
		handleBadRequest(w, "request body malformed")
		return
	}

	// Create team if it doesnt exist
	team, err := createTeam(teamName, grafanaURL, grafanaBasicAuth)

	// List the users in the team
	usersInTeam, err := getTeamMembers(team, grafanaURL, grafanaBasicAuth)

	if err != nil {
		handleInternalServerError(w, "Error listing users in team: "+teamName, err.Error())
	}

	// Remove any members who are in the team but not the PUT payload
	for _, u := range usersInTeam {
		if userInList(u, users) == false {
			err = removeUserFromTeam(u, team, grafanaURL, grafanaBasicAuth)
			if err != nil {
				handleInternalServerError(w, "Error removing user: "+u.Email+" from team: "+team.Name+" error: ", err.Error())
			}
		}
	}

	allUsers, err := getAllUsers(grafanaURL, grafanaBasicAuth)

	if err != nil {
		handleInternalServerError(w, "Error fetching users from grafana, error: ", err.Error())
	}

	// Delete any users who are not in the PUT payload
	for _, u := range allUsers {
		if userInList(u, users) == false && u.Id != 1 {
			err = deleteUserById(u.Id, grafanaURL, grafanaBasicAuth)
			if err != nil {
				handleInternalServerError(w, "Error deleting user from grafana, error: ", err.Error())
			}
		}
	}

	// Create a slice of users to form the response body which will include IDs not sent in PUT payload
	var agentResponse []User

	for _, u := range users {

		// Create global users for each email in the PUT payload
		user, err := createUser(u, grafanaURL, grafanaBasicAuth)

		if err != nil {
			handleInternalServerError(w, "Error creating user: "+u.Email, err.Error())
			return
		}

		// Append the user including their ID to the user slice
		agentResponse = append(agentResponse, user)

		// Add the user to the team if they arent already in it
		logrus.Infof("Adding user with id %s to team %s", strconv.FormatInt(user.Id, 10), strconv.FormatInt(team.TeamId, 10))
		err = addUserToTeam(user, team, grafanaURL, grafanaBasicAuth)

		if err != nil {
			handleInternalServerError(w, "Error adding user: "+u.Email+" to team: "+team.Name, err.Error())
			return
		}
	}
	// Return list of users created including IDs
	agentResponseBody, err := json.Marshal(agentResponse)
	handleSuccess(w, agentResponseBody)
}
