/*
 * hub-grafana-agent
 *
 * an agent used to provision and configure Grafana resources
 *
 * API version: v1beta
 * Contact: support@appvia.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The definition of a dashboard
type Dashboard struct {

	// The name of this dashboard
	Name string `json:"name"`

	// The url of this dashboard
	Url string `json:"url"`

	// The uid of this dashboard
	Uid string `json:"uid"`

	// The id of this dashboard
	Id int64 `json:"id"`
}
