/*
 * hub-grafana-agent
 *
 * an agent used to provision and configure Grafana resources
 *
 * API version: v1beta
 * Contact: support@appvia.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The definition of a team
type Team struct {
	// The name of this team
	Name string `json:"name"`
	// The email of this team
	Email string `json:"email,omitempty"`
	// The id of this team
	TeamId int64 `json:"id,omitempty"`
}
