/*
 * hub-grafana-agent
 *
 * an agent used to provision and configure Grafana resources
 *
 * API version: v1beta
 * Contact: support@appvia.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The definition of a dashboard
type Dashboard struct {

	// The namespace this dashboard is for
	Namespace string `json:"namespace"`

	// The url of this dashboard
	Url string `json:"url"`
}
