/*
 * hub-grafana-agent
 *
 * an agent used to provision and configure Grafana resources
 *
 * API version: v1beta
 * Contact: support@appvia.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The definition of a user
type User struct {
	// The name of this user
	Name string `json:"name"`
	// The email of this user
	Email string `json:"email"`
	// The username of this user
	Username string `json:"login,omitempty"`
	// The id of this user
	Id int64 `json:"id,omitempty"`
	// The password of this user
	Password string `json:"password,omitempty"`
}
