/*
 * hub-grafana-agent
 *
 * an agent used to provision and configure Grafana resources
 *
 * API version: v1beta
 * Contact: support@appvia.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Is a generic error event returned when the we have an internal error
type ApiError struct {

	// A human readable description used to define what error has occured
	Reason string `json:"reason"`

	// Additional details related to the error
	Detail string `json:"detail,omitempty"`
}
