/*
 * hub-grafana-agent
 *
 * an agent used to provision and configure Grafana resources
 *
 * API version: v1beta
 * Contact: support@appvia.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/api/v1beta/",
		Index,
	},

	Route{
		"DashboardNameDelete",
		strings.ToUpper("Delete"),
		"/api/v1beta/dashboard/{namespace}",
		DashboardNameDelete,
	},

	Route{
		"DashboardNameGet",
		strings.ToUpper("Get"),
		"/api/v1beta/dashboard/{namespace}",
		DashboardNameGet,
	},

	Route{
		"DashboardNamePut",
		strings.ToUpper("Put"),
		"/api/v1beta/dashboard/{namespace}",
		DashboardNamePut,
	},

	Route{
		"HealthzGet",
		strings.ToUpper("Get"),
		"/api/v1beta/healthz",
		HealthzGet,
	},
}
